package com.board.model.dao;
// Generated 2020. 3. 26 ���� 1:30:31 by Hibernate Tools 5.2.12.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NoticeBoard generated by hbm2java
 */
@Entity
@Table(name = "notice_board", catalog = "boarddb")
@NamedQueries({
	@NamedQuery(name = "notice_board.showAll", query = NoticeBoard.GET_NOTICE_ALL_QUERY),
	@NamedQuery(name = "notice_board.detail", query = NoticeBoard.GET_NOTICE_QUERY),
	@NamedQuery(name = "notice_board.update", query = NoticeBoard.GET_NOTICE_UPDATE_QUERY),
	@NamedQuery(name = "notice_board.updateView", query = NoticeBoard.GET_NOTICE_UPDATE_VIEW_QUERY)
})
public class NoticeBoard implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	static final String GET_NOTICE_ALL_QUERY = "select n from NoticeBoard n order by n.id desc";
	static final String GET_NOTICE_QUERY = "from NoticeBoard n where n.id = :id";
	static final String GET_NOTICE_UPDATE_QUERY = "update NoticeBoard n "
			+ "set title = :title, content = :content, file = :file where n.id = :id";
	static final String GET_NOTICE_UPDATE_VIEW_QUERY = "update NoticeBoard n set view = view + 1 where n.id = :id";
	
	private Integer id;
	private String title;
	private String author;
	private String content;
	private Date date;
	private String file;
	private Integer view;

	public NoticeBoard() {
	}
	
	//Update View + 1 
	public NoticeBoard(Integer id, Integer view) {
		this.id = id;
		this.view = view;
	}
	
	//Update or Edit purpose only
	public NoticeBoard(Integer id, String title, String content, String file) {
		this.id = id;
		this.title = title;
		this.content = content;
		this.file = file;
	}

	public NoticeBoard(String title, String author, String content, Date date, Integer view) {
		this.title = title;
		this.author = author;
		this.content = content;
		this.date = date;
		this.view = view;
	}

	public NoticeBoard(String title, String author, String content, Date date, String file, Integer view) {
		this.title = title;
		this.author = author;
		this.content = content;
		this.date = date;
		this.file = file;
		this.view = view;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "TITLE", nullable = false, length = 150)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "AUTHOR", nullable = false, length = 80)
	public String getAuthor() {
		return this.author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	@Column(name = "CONTENT", nullable = false, length = 16777215)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE", nullable = false, length = 19)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "FILE")
	public String getFile() {
		return this.file;
	}

	public void setFile(String file) {
		this.file = file;
	}
	
	@Column(name = "VIEW", nullable = false)
	public Integer getView() {
		return this.view;
	}

	public void setView(Integer view) {
		this.view = view;
	}

}
